import { CampingSite } from './types'

export const SITE_PRICES = {
  single: 60000,
  family: 120000,
} as const

export const CAMPING_SITES: CampingSite[] = [
  {
    id: 1,
    name: 'A-1 솔바람 사이트',
    type: 'single',
    location: '계곡 인접 / 입구에서 도보 2분',
    size: '8m × 8m',
    features: ['계곡 조망', '그늘 풍부', '전기 콘센트', '개수대 근접'],
    capacity: 4,
    price: 60000,
    images: ['/sites/site1-1.jpg', '/sites/site1-2.jpg'],
    description: '법흥계곡 바로 옆에 위치해 물소리를 들으며 힐링할 수 있는 사이트입니다. 큰 소나무 그늘이 여름에도 시원합니다.',
  },
  {
    id: 2,
    name: 'A-2 계곡뷰 사이트',
    type: 'single',
    location: '계곡 인접 / 입구에서 도보 3분',
    size: '8m × 8m',
    features: ['계곡 직접 접근', '전기 콘센트', '평탄한 지형', '화장실 근접'],
    capacity: 4,
    price: 60000,
    images: ['/sites/site2-1.jpg', '/sites/site2-2.jpg'],
    description: '계곡에 직접 발 담그기 좋은 위치의 사이트입니다. 지형이 평탄해 텐트 설치가 편리합니다.',
  },
  {
    id: 3,
    name: 'A-3 숲속 사이트',
    type: 'single',
    location: '숲 속 / 입구에서 도보 4분',
    size: '9m × 8m',
    features: ['사방 나무로 둘러싸임', '아늑한 분위기', '전기 콘센트', '프라이버시 우수'],
    capacity: 4,
    price: 60000,
    images: ['/sites/site3-1.jpg', '/sites/site3-2.jpg'],
    description: '나무들로 둘러싸인 아늑한 숲속 사이트입니다. 프라이버시가 보장되어 조용히 쉬고 싶은 분들께 추천합니다.',
  },
  {
    id: 4,
    name: 'A-4 산뷰 사이트',
    type: 'single',
    location: '경사지 상단 / 입구에서 도보 5분',
    size: '8m × 9m',
    features: ['산 전망 우수', '일출 명소', '전기 콘센트', '탁 트인 뷰'],
    capacity: 4,
    price: 60000,
    images: ['/sites/site4-1.jpg', '/sites/site4-2.jpg'],
    description: '영월의 아름다운 산 전망을 즐길 수 있는 사이트입니다. 맑은 날 일출이 특히 아름답습니다.',
  },
  {
    id: 5,
    name: 'A-5 잔디 사이트',
    type: 'single',
    location: '중앙 잔디광장 인접',
    size: '8m × 8m',
    features: ['잔디밭 인접', '아이들 놀기 좋음', '전기 콘센트', '화장실 근접'],
    capacity: 4,
    price: 60000,
    images: ['/sites/site5-1.jpg', '/sites/site5-2.jpg'],
    description: '넓은 잔디광장 바로 옆에 위치해 아이들이 자유롭게 뛰놀기 좋은 사이트입니다.',
  },
  {
    id: 6,
    name: 'A-6 하늘 사이트',
    type: 'single',
    location: '캠핑장 최상단',
    size: '9m × 9m',
    features: ['별 관측 최적', '넓은 공간', '전기 콘센트', '조용한 위치'],
    capacity: 4,
    price: 60000,
    images: ['/sites/site6-1.jpg', '/sites/site6-2.jpg'],
    description: '캠핑장 최상단에 위치해 밤하늘 별 관측이 가장 잘 되는 사이트입니다. 광공해가 적어 은하수도 볼 수 있습니다.',
  },
  {
    id: 7,
    name: 'B-1 가족 계곡 사이트',
    type: 'family',
    location: '계곡 인접 / 넓은 구역',
    size: '12m × 10m',
    features: ['계곡 조망', '2팀 동시 사용', '전기 콘센트 2개', '바베큐 공간'],
    capacity: 8,
    price: 120000,
    images: ['/sites/site7-1.jpg', '/sites/site7-2.jpg'],
    description: '두 가족이 함께 사용할 수 있는 넓은 계곡 인접 사이트입니다. 바베큐 공간이 마련되어 있어 함께 식사하기 좋습니다.',
  },
  {
    id: 8,
    name: 'B-2 가족 숲속 사이트',
    type: 'family',
    location: '숲 속 / 넓은 구역',
    size: '12m × 10m',
    features: ['숲속 분위기', '2팀 동시 사용', '전기 콘센트 2개', '해먹 설치 가능'],
    capacity: 8,
    price: 120000,
    images: ['/sites/site8-1.jpg', '/sites/site8-2.jpg'],
    description: '넓은 숲속 공간에 두 가족이 여유롭게 사용할 수 있는 사이트입니다. 해먹을 걸 수 있는 나무들이 있습니다.',
  },
  {
    id: 9,
    name: 'B-3 가족 잔디 사이트',
    type: 'family',
    location: '잔디광장 인접 / 넓은 구역',
    size: '14m × 10m',
    features: ['가장 넓은 공간', '2팀 동시 사용', '전기 콘센트 2개', '아이놀이 최적'],
    capacity: 10,
    price: 120000,
    images: ['/sites/site9-1.jpg', '/sites/site9-2.jpg'],
    description: '캠핑장에서 가장 넓은 사이트입니다. 잔디광장과 연결되어 아이들이 있는 두 가족에게 최적입니다.',
  },
  {
    id: 10,
    name: 'B-4 가족 파노라마 사이트',
    type: 'family',
    location: '전망 좋은 구역',
    size: '12m × 11m',
    features: ['파노라마 전망', '2팀 동시 사용', '전기 콘센트 2개', '일몰 명소'],
    capacity: 8,
    price: 120000,
    images: ['/sites/site10-1.jpg', '/sites/site10-2.jpg'],
    description: '법흥계곡 전체를 조망할 수 있는 파노라마 뷰가 일품인 사이트입니다. 특히 저녁 일몰이 아름답습니다.',
  },
]

export const CAMPING_INFO = {
  name: '법흥계곡캠핑오늘',
  address: '강원 영월군 무릉도원면 법흥리 115-3',
  phone: '033-000-0000',
  checkIn: '14:00',
  checkOut: '11:00',
  description: '강원 영월 법흥계곡 옆에 자리한 자연 친화적 캠핑장입니다.',
}
